### ISSUE TITLE
View streams over VPN problems

### ISSUE THREAD

**Issue by NathanBlais** [DispatchCommit/BitWave#1]
Streams will not play on any browser I try to use which includes Safari, Chrome, Firefox, Beaker and others when I am using my VPN. I get the message "The media could not be loaded, either because the server or network failed or because the format is not supported." regardless of the stream I choose.

**Comment by DispatchCommit** [comment]
Are you using a VPN program installed system wide or a browser plugin?

Could you open the developer panel and do a hard refresh to show which files are failing? I suspect it may be related to HSTS policies.

**Comment by MemeScreen** [comment]
I am using the Nord VPN IKE app for Mac OS. 

<img width="1303" alt="Screen Shot 2019-03-26 at 7 09 20 PM" src="https://user-images.githubusercontent.com/37645161/55045453-10473b00-4ffb-11e9-9eeb-2ebf11a888d9.png">

**Comment by DispatchCommit** [comment]
The endpoints have been improved. Should work now. If not, try to use a system wide VPN over just a browser plugin that may strip, change, or adjust headers and file responses.
