### ISSUE TITLE
Boomer fails at strawming

### ISSUE THREAD

**Issue by fannyAbDabs** [DispatchCommit/BitWave#2]
Started a stream tonight, the drop rate went to 40% and climbing so stopped it.  Fucked around with bitrate, tried to restart.  Got 'Failed to connect to server' in OBS.  Left it for 30 mins and retried, same result.  Meanwhile 15 seconds of the previous upload is looping.  Does bitwave kill a channel after an inactivity period?  That would allow noobs like me to fuck around getting things working.

Streaming from the jolly uk to US probably doesn't help.

**Comment by DispatchCommit** [comment]
Appears to be an ongoing issue. Most likely need to establish an ingestion server closer to you.
